import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { type LessonPlan, type SchemeOfWork, getProfile } from './db';

export async function exportLessonPlanToPDF(plan: LessonPlan) {
  const profile = await getProfile();
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  let y = 15;

  // Header
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(profile?.schoolName || 'School Name', pageWidth / 2, y, { align: 'center' });
  y += 7;
  doc.setFontSize(12);
  doc.text('LESSON PLAN', pageWidth / 2, y, { align: 'center' });
  y += 4;
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Details table
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  const details = [
    ['Subject:', plan.subject, 'Class:', plan.classLevel],
    ['Date:', plan.date, 'Duration:', plan.duration],
    ['Term:', `Term ${plan.term}`, 'Week:', `Week ${plan.week}`],
    ['Topic:', plan.topic, '', ''],
    ['Sub-topic:', plan.subTopic, '', ''],
  ];

  autoTable(doc, {
    startY: y,
    body: details,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 3 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 30 },
      1: { cellWidth: 55 },
      2: { fontStyle: 'bold', cellWidth: 30 },
      3: { cellWidth: 55 },
    },
    margin: { left: margin, right: margin },
  });

  y = (doc as any).lastAutoTable.finalY + 6;

  // Performance Objectives
  doc.setFont('helvetica', 'bold');
  doc.text('PERFORMANCE OBJECTIVES:', margin, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  plan.objectives.forEach((obj, i) => {
    const text = `${i + 1}. ${obj}`;
    const lines = doc.splitTextToSize(text, pageWidth - 2 * margin);
    doc.text(lines, margin + 3, y);
    y += lines.length * 5;
  });
  y += 3;

  // Entry Behaviour
  doc.setFont('helvetica', 'bold');
  doc.text('ENTRY BEHAVIOUR:', margin, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  const entryLines = doc.splitTextToSize(plan.entryBehaviour, pageWidth - 2 * margin);
  doc.text(entryLines, margin + 3, y);
  y += entryLines.length * 5 + 3;

  // Instructional Materials
  doc.setFont('helvetica', 'bold');
  doc.text('INSTRUCTIONAL MATERIALS:', margin, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.text(plan.materials.join(', '), margin + 3, y);
  y += 7;

  // Reference
  if (plan.references) {
    doc.setFont('helvetica', 'bold');
    doc.text('REFERENCE:', margin, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.text(plan.references, margin + 3, y);
    y += 7;
  }

  // Check if we need a new page
  if (y > 230) {
    doc.addPage();
    y = 15;
  }

  // Presentation Steps
  doc.setFont('helvetica', 'bold');
  doc.text('PRESENTATION (Step-by-Step):', margin, y);
  y += 3;

  const stepsData = plan.steps.map((s, i) => [
    `Step ${i + 1}`,
    s.teacherActivity,
    s.studentActivity,
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Step', 'Teacher Activity', 'Student Activity']],
    body: stepsData,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [15, 107, 79], fontStyle: 'bold' },
    columnStyles: {
      0: { cellWidth: 18 },
    },
    margin: { left: margin, right: margin },
  });

  y = (doc as any).lastAutoTable.finalY + 6;

  if (y > 250) {
    doc.addPage();
    y = 15;
  }

  // Evaluation
  doc.setFont('helvetica', 'bold');
  doc.text('EVALUATION:', margin, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  const evalLines = doc.splitTextToSize(plan.evaluation, pageWidth - 2 * margin);
  doc.text(evalLines, margin + 3, y);
  y += evalLines.length * 5 + 3;

  // Assignment
  doc.setFont('helvetica', 'bold');
  doc.text('ASSIGNMENT:', margin, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  const assignLines = doc.splitTextToSize(plan.assignment, pageWidth - 2 * margin);
  doc.text(assignLines, margin + 3, y);
  y += assignLines.length * 5 + 10;

  // Teacher signature line
  doc.setFont('helvetica', 'normal');
  doc.text('Teacher\'s Signature: ___________________', margin, y);
  doc.text('Date: _______________', pageWidth - margin - 50, y);

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 10;
  doc.setFontSize(8);
  doc.setTextColor(128);
  doc.text(`Generated by NaijaLesson • ${profile?.name || 'Teacher'}`, pageWidth / 2, footerY, { align: 'center' });

  doc.save(`${plan.subject}_${plan.classLevel}_Week${plan.week}_LessonPlan.pdf`);
}

export async function exportSOWToPDF(sow: SchemeOfWork) {
  const profile = await getProfile();
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  let y = 15;

  // Header
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(profile?.schoolName || 'School Name', pageWidth / 2, y, { align: 'center' });
  y += 7;
  doc.setFontSize(12);
  doc.text('SCHEME OF WORK', pageWidth / 2, y, { align: 'center' });
  y += 4;
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Info
  doc.setFontSize(10);
  doc.text(`Subject: ${sow.subject}`, margin, y);
  doc.text(`Class: ${sow.classLevel}`, pageWidth / 2, y);
  y += 5;
  doc.text(`Term: ${sow.term}`, margin, y);
  doc.text(`Year: ${sow.year}`, pageWidth / 2, y);
  y += 8;

  // Table
  const tableData = sow.weeks.map(w => [
    `${w.week}`,
    w.topic,
    w.subTopic,
    w.objectives.join('; '),
    w.materials.join(', '),
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Week', 'Topic', 'Sub-topic', 'Objectives', 'Materials']],
    body: tableData,
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [15, 107, 79], fontStyle: 'bold' },
    columnStyles: {
      0: { cellWidth: 12 },
      1: { cellWidth: 30 },
      2: { cellWidth: 35 },
      3: { cellWidth: 55 },
      4: { cellWidth: 35 },
    },
    margin: { left: margin, right: margin },
  });

  const footerY = doc.internal.pageSize.getHeight() - 10;
  doc.setFontSize(8);
  doc.setTextColor(128);
  doc.text(`Generated by NaijaLesson • ${profile?.name || 'Teacher'}`, pageWidth / 2, footerY, { align: 'center' });

  doc.save(`SOW_${sow.subject}_${sow.classLevel}_Term${sow.term}.pdf`);
}
