project_id = "xhlnraxpfiditioibdnj"

[functions.generate-lesson]
verify_jwt = false

[functions.copy-note-chat]
verify_jwt = false

[functions.generate-assessment]
verify_jwt = false

[functions.review-lesson]
verify_jwt = false
