import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Briefcase, FileText, PenLine, BookOpen, Users, Download, BarChart3 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { getProfile, getAllLessonPlans, getAllSOW, getAllAINotes, type TeacherProfile } from '@/lib/db';
import { getAllClassGroups, getTopicAverages, getAtRiskStudents, type ClassGroup } from '@/lib/db-tracker';
import { getAllSavedResources } from '@/lib/db-resources';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { toast } from 'sonner';

interface PortfolioData {
  profile: TeacherProfile | null;
  lessonPlans: any[];
  aiNotes: any[];
  sows: any[];
  classGroups: ClassGroup[];
  resourceCount: number;
}

export default function Portfolio() {
  const [data, setData] = useState<PortfolioData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      const [profile, lessonPlans, sows, aiNotes, classGroups, resources] = await Promise.all([
        getProfile(),
        getAllLessonPlans(),
        getAllSOW(),
        getAllAINotes(),
        getAllClassGroups(),
        getAllSavedResources(),
      ]);
      setData({ profile: profile || null, lessonPlans, aiNotes, sows, classGroups, resourceCount: resources.length });
      setLoading(false);
    }
    load();
  }, []);

  const handleExportPDF = async () => {
    if (!data) return;
    const doc = new jsPDF('p', 'mm', 'a4');
    const pw = doc.internal.pageSize.getWidth();
    const m = 15;
    let y = 15;

    // Header
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('TEACHER PORTFOLIO & APPRAISAL REPORT', pw / 2, y, { align: 'center' });
    y += 5;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by Syllabix NG', pw / 2, y, { align: 'center' });
    y += 3;
    doc.setLineWidth(0.5);
    doc.line(m, y, pw - m, y);
    y += 8;

    // Teacher info
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('TEACHER INFORMATION', m, y);
    y += 6;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Name: ${data.profile?.name || 'N/A'}`, m, y); y += 5;
    doc.text(`School: ${data.profile?.schoolName || 'N/A'}`, m, y); y += 5;
    doc.text(`Subjects: ${data.profile?.subjects?.join(', ') || 'N/A'}`, m, y); y += 5;
    doc.text(`Report Date: ${new Date().toLocaleDateString('en-NG')}`, m, y); y += 10;

    // Summary
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('ACTIVITY SUMMARY', m, y); y += 3;

    autoTable(doc, {
      startY: y,
      body: [
        ['Lesson Plans Generated', String(data.lessonPlans.length)],
        ['AI Copy Notes Generated', String(data.aiNotes.length)],
        ['Schemes of Work', String(data.sows.length)],
        ['Classes Managed', String(data.classGroups.length)],
        ['Total Students Tracked', String(data.classGroups.reduce((s, g) => s + g.students.length, 0))],
        ['Saved Resources', String(data.resourceCount)],
      ],
      theme: 'grid',
      styles: { fontSize: 10, cellPadding: 3 },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 100 }, 1: { cellWidth: 60 } },
      margin: { left: m, right: m },
    });
    y = (doc as any).lastAutoTable.finalY + 8;

    // Lesson Plans detail
    if (data.lessonPlans.length > 0) {
      if (y > 230) { doc.addPage(); y = 15; }
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('LESSON PLANS LOG', m, y); y += 3;

      autoTable(doc, {
        startY: y,
        head: [['Date', 'Subject', 'Class', 'Topic', 'Status']],
        body: data.lessonPlans.map(p => [
          p.date || p.createdAt?.split('T')[0] || '',
          p.subject,
          p.classLevel,
          p.topic,
          p.status,
        ]),
        theme: 'grid',
        styles: { fontSize: 8, cellPadding: 2 },
        headStyles: { fillColor: [15, 107, 79] },
        margin: { left: m, right: m },
      });
      y = (doc as any).lastAutoTable.finalY + 8;
    }

    // Teaching effectiveness
    if (data.classGroups.length > 0) {
      if (y > 200) { doc.addPage(); y = 15; }
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('TEACHING EFFECTIVENESS', m, y); y += 6;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);

      for (const group of data.classGroups) {
        if (y > 240) { doc.addPage(); y = 15; }
        doc.setFont('helvetica', 'bold');
        doc.text(`${group.name} (${group.subject} — ${group.classLevel})`, m, y); y += 5;
        doc.setFont('helvetica', 'normal');

        const averages = getTopicAverages(group);
        if (averages.length > 0) {
          const overallAvg = Math.round(averages.reduce((s, a) => s + a.average, 0) / averages.length);
          doc.text(`Overall class average: ${overallAvg}%`, m + 3, y); y += 5;

          const weak = averages.filter(a => a.average < 50);
          if (weak.length > 0) {
            doc.text(`Topics needing remediation: ${weak.map(w => w.topic).join(', ')}`, m + 3, y); y += 5;
          }
        }

        const atRisk = getAtRiskStudents(group);
        if (atRisk.length > 0) {
          doc.text(`At-risk students identified: ${atRisk.length}`, m + 3, y); y += 5;
        }
        y += 3;
      }
    }

    // Footer
    const footerY = doc.internal.pageSize.getHeight() - 10;
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text(`Generated by Syllabix NG • ${new Date().toLocaleDateString('en-NG')}`, pw / 2, footerY, { align: 'center' });

    doc.save(`Portfolio_${data.profile?.name?.replace(/\s+/g, '_') || 'Teacher'}_${new Date().toISOString().split('T')[0]}.pdf`);
    toast.success('Portfolio exported as PDF');
  };

  if (loading || !data) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="h-8 w-8 border-2 border-primary border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  const totalStudents = data.classGroups.reduce((s, g) => s + g.students.length, 0);

  return (
    <div className="pb-28 px-4 pt-4">
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="space-y-5">
        <div className="flex items-center justify-between">
          <h2 className="text-xl font-heading font-bold">My Portfolio</h2>
          <Button size="sm" onClick={handleExportPDF}>
            <Download className="h-4 w-4 mr-1" /> Export PDF
          </Button>
        </div>

        {/* Teacher info card */}
        <div className="glass-card rounded-2xl p-5">
          <div className="flex items-center gap-3 mb-3">
            <div className="h-12 w-12 rounded-full bg-primary/20 flex items-center justify-center">
              <Briefcase className="h-6 w-6 text-primary" />
            </div>
            <div>
              <p className="font-heading font-bold">{data.profile?.name || 'Teacher'}</p>
              <p className="text-xs text-muted-foreground">{data.profile?.schoolName || 'School'}</p>
              <p className="text-xs text-muted-foreground">{data.profile?.subjects?.join(', ')}</p>
            </div>
          </div>
        </div>

        {/* Stats grid */}
        <div className="grid grid-cols-2 gap-3">
          <div className="glass-card rounded-xl p-4 flex items-center gap-3">
            <div className="p-2 rounded-lg bg-primary/10"><FileText className="h-5 w-5 text-primary" /></div>
            <div>
              <p className="text-xl font-bold">{data.lessonPlans.length}</p>
              <p className="text-[10px] text-muted-foreground">Lesson Plans</p>
            </div>
          </div>
          <div className="glass-card rounded-xl p-4 flex items-center gap-3">
            <div className="p-2 rounded-lg bg-primary/10"><PenLine className="h-5 w-5 text-primary" /></div>
            <div>
              <p className="text-xl font-bold">{data.aiNotes.length}</p>
              <p className="text-[10px] text-muted-foreground">Copy Notes</p>
            </div>
          </div>
          <div className="glass-card rounded-xl p-4 flex items-center gap-3">
            <div className="p-2 rounded-lg bg-primary/10"><BookOpen className="h-5 w-5 text-primary" /></div>
            <div>
              <p className="text-xl font-bold">{data.sows.length}</p>
              <p className="text-[10px] text-muted-foreground">Schemes of Work</p>
            </div>
          </div>
          <div className="glass-card rounded-xl p-4 flex items-center gap-3">
            <div className="p-2 rounded-lg bg-primary/10"><Users className="h-5 w-5 text-primary" /></div>
            <div>
              <p className="text-xl font-bold">{totalStudents}</p>
              <p className="text-[10px] text-muted-foreground">Students Tracked</p>
            </div>
          </div>
        </div>

        {/* Class performance summary */}
        {data.classGroups.length > 0 && (
          <div className="glass-card rounded-xl p-4 space-y-3">
            <div className="flex items-center gap-2">
              <BarChart3 className="h-4 w-4 text-primary" />
              <h3 className="text-sm font-heading font-semibold">Teaching Effectiveness</h3>
            </div>
            {data.classGroups.map(group => {
              const avgs = getTopicAverages(group);
              const overallAvg = avgs.length > 0 ? Math.round(avgs.reduce((s, a) => s + a.average, 0) / avgs.length) : null;
              const atRisk = getAtRiskStudents(group);
              return (
                <div key={group.id} className="border border-border/50 rounded-lg p-3 space-y-1">
                  <p className="text-xs font-semibold">{group.name}</p>
                  <div className="flex items-center gap-4 text-[10px] text-muted-foreground">
                    <span>{group.students.length} students</span>
                    {overallAvg !== null && <span className={overallAvg < 50 ? 'text-destructive' : 'text-primary'}>{overallAvg}% avg</span>}
                    {atRisk.length > 0 && <span className="text-destructive">{atRisk.length} at-risk</span>}
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {/* Recent activity */}
        {data.lessonPlans.length > 0 && (
          <div className="glass-card rounded-xl p-4 space-y-3">
            <h3 className="text-sm font-heading font-semibold">Recent Lesson Plans</h3>
            {data.lessonPlans.slice(-5).reverse().map(p => (
              <div key={p.id} className="flex items-center justify-between py-1.5">
                <div>
                  <p className="text-xs font-medium">{p.topic}</p>
                  <p className="text-[10px] text-muted-foreground">{p.subject} • {p.classLevel}</p>
                </div>
                <span className="text-[10px] text-muted-foreground">{p.date || p.createdAt?.split('T')[0]}</span>
              </div>
            ))}
          </div>
        )}
      </motion.div>
    </div>
  );
}
