// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my teacher profile",
  description: "Return the signed-in teacher's Syllabix profile: display name, workspace role and school workspace code.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("display_name, role, school_code, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "No profile found for this account yet." }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/lookup-curriculum.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@3.25.76";
var lookup_curriculum_default = defineTool2({
  name: "lookup_curriculum",
  title: "Look up verified curriculum topics",
  description: "Look up verified NERDC-grounded curriculum topics and learning objectives by subject, class level, term and week.",
  inputSchema: {
    subject: z.string().trim().min(1).describe("Subject, e.g. Mathematics."),
    classLevel: z.string().trim().min(1).describe("Class level, e.g. 'JSS 1'."),
    term: z.number().int().min(1).max(3).optional().describe("Term 1-3. Omit for all terms."),
    week: z.number().int().min(1).max(13).optional().describe("Week 1-13. Omit for all weeks.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ subject, classLevel, term, week }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("curriculum_topics").select("subject, class_level, term, week, topic, sub_topic, learning_objectives, source, source_url").eq("subject", subject).eq("class_level", classLevel).eq("verified", true).order("term").order("week").limit(60);
    if (typeof term === "number") query = query.eq("term", term);
    if (typeof week === "number") query = query.eq("week", week);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return {
        content: [
          {
            type: "text",
            text: `No verified curriculum found for ${subject} / ${classLevel}. Content for this slot is not curriculum-verified yet.`
          }
        ]
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { topics: data }
    };
  }
});

// src/lib/mcp/tools/list-schemes.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@3.25.76";
var list_schemes_default = defineTool3({
  name: "list_shared_schemes",
  title: "List shared schemes of work",
  description: "List schemes of work shared in the signed-in teacher's school workspace, optionally filtered by subject, class level, term or status.",
  inputSchema: {
    subject: z2.string().trim().min(1).optional().describe("Filter by subject."),
    classLevel: z2.string().trim().min(1).optional().describe("Filter by class level, e.g. 'JSS 2'."),
    term: z2.number().int().min(1).max(3).optional().describe("Filter by term 1-3."),
    status: z2.string().trim().min(1).optional().describe("Filter by review status, e.g. 'pending' or 'approved'."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ subject, classLevel, term, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("shared_schemes").select("id, subject, class_level, term, year, status, user_id, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (subject) query = query.eq("subject", subject);
    if (classLevel) query = query.eq("class_level", classLevel);
    if (typeof term === "number") query = query.eq("term", term);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { schemes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-scheme.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@3.25.76";
var get_scheme_default = defineTool4({
  name: "get_shared_scheme",
  title: "Get a shared scheme of work",
  description: "Fetch the full weekly breakdown of one shared scheme of work by its id, including all weekly topics and notes.",
  inputSchema: {
    id: z3.string().uuid().describe("The scheme id returned by list_shared_schemes.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("shared_schemes").select("id, subject, class_level, term, year, status, weeks, created_at, updated_at").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "No scheme found with that id in your workspace." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { scheme: data }
    };
  }
});

// src/lib/mcp/tools/comment-on-scheme.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@3.25.76";
var comment_on_scheme_default = defineTool5({
  name: "comment_on_scheme",
  title: "Comment on a shared scheme",
  description: "Add a review comment to a shared scheme of work in the signed-in teacher's school workspace.",
  inputSchema: {
    schemeId: z4.string().uuid().describe("The scheme id to comment on."),
    comment: z4.string().trim().min(1).max(2e3).describe("The comment text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ schemeId, comment }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("scheme_comments").insert({ scheme_id: schemeId, comment, user_id: ctx.getUserId() }).select("id, scheme_id, comment, created_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { comment: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xhlnraxpfiditioibdnj";
var mcp_default = defineMcp({
  name: "syllabix",
  title: "Syllabix",
  version: "0.1.0",
  instructions: "Tools for Syllabix, an offline-first lesson planning app for Nigerian teachers. Use `lookup_curriculum` for verified NERDC topics and objectives, `list_shared_schemes` and `get_shared_scheme` to read schemes of work shared in the teacher's school workspace, `comment_on_scheme` to leave review feedback, and `get_my_profile` for the signed-in teacher's workspace context.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    lookup_curriculum_default,
    list_schemes_default,
    get_scheme_default,
    comment_on_scheme_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
